### ISSUE TITLE
Ubuntuh环境下执行 python generate/run.py 出现 Exception: no type: c_int

### ISSUE THREAD

**Issue by tdzhang** [haifengat/hf_ctp_py_proxy#12]
Traceback (most recent call last):
  File "generate/run.py", line 34, in <module>
    g_c_py.run(True, True) # 生成c+  py
  File "/root/hf_ctp_py_proxy/generate/g_c_py.py", line 469, in run
    raise Exception(f'no type: {type_name}')
Exception: no type: c_int

**Comment by haifengat** [comment]
已修复,原因是没有处理short类型

**Comment by wlb632363** [comment]
> 已修复,原因是没有处理short类型

环境：linux
gcc: 8.3.0
python: 3.6

运行时还是有异常
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    g_c_py.run(True, True) # 生成c+  py
  File "/kfdata/pythonCode/ctp/hf_ctp_py_proxy/generate/g_c_py.py", line 486, in run
    raise Exception(f'no type: {type_name}')
Exception: no type: c_int
