### ISSUE TITLE
运行 pyton generate\\run.py 报错

### ISSUE THREAD

**Issue by wlb632363** [haifengat/hf_ctp_py_proxy#17]
环境：linux x64
gcc: 8.3.0
python: 3.6

**运行 pyton generate\\run.py 报错**

Traceback (most recent call last):
  File "generate/run.py", line 36, in <module>
    g_c_py.run(True, True) # 生成c+  py
  File "/kfdata/pythonCode/ctp/hf_ctp_py_proxy/generate/g_c_py.py", line 486, in run
    raise Exception(f'no type: {type_name}')
Exception: no type: c_int

**Comment by lancelove** [comment]
你解决了吗 我也遇到这个问题了
