### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xiaodonggua1** [haifengat/hf_ctp_py_proxy#18]
Traceback (most recent call last):
  File "D:/deyaTrade/test_api", line 82, in <module>
    tt = TestTrade(front_trade, broker, investor, pwd, appid, auth_code, proc)
  File "D:/deyaTrade/test_api", line 23, in __init__
    self.t = CtpTrade()
  File "C:\Program Files\python36\lib\site-packages\py_ctp\trade.py", line 49, in __init__
    self.t = Trade()
  File "C:\Program Files\python36\lib\site-packages\py_ctp\ctp_trade.py", line 36, in __init__
    self.h = CDLL(absolute_dllfile_path)
  File "C:\Program Files\python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by xiaodonggua1** [comment]
用的是https://pypi.org/project/py-ctp/的测试代码
