### ISSUE TITLE
2.2.2 linux 下报错

### ISSUE THREAD

**Issue by edwardsun** [haifengat/hf_ctp_py_proxy#19]
2.2.2在linux下出现这个错误。
2.2.0没有问题。

Traceback (most recent call last):
  File "/home/ctp_prod/.local/lib/python3.6/site-packages/py_ctp/trade.py", line 49, in __init__
    self.t = Trade()
  File "/home/ctp_prod/.local/lib/python3.6/site-packages/py_ctp/ctp_trade.py", line 32, in __init__
    os.environ['path'] += f';{dlldir}'
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'path'

**Comment by cqBRYANT** [comment]
我也遇到了这个问题，系统是ubuntu16.04，望修复此问题。

**Comment by edwardsun** [comment]
已经修复
