### ISSUE TITLE
function 'RegisterUserSystemInfo' not found

### ISSUE THREAD

**Issue by kennyoysj** [haifengat/hf_ctp_py_proxy#29]
Traceback (most recent call last):
  File "I:/pythonWorkSpace/ctpServer/ai/iknow/ouyang/ctpTest.py", line 80, in <module>
    tt = TestTrade(front_trade, broker, investor, pwd, appid, auth_code)
  File "I:/pythonWorkSpace/ctpServer/ai/iknow/ouyang/ctpTest.py", line 24, in __init__
    self.t = CtpTrade()
  File "I:\pythonWorkSpace\ctpServer\ai\iknow\ouyang\trade.py", line 50, in __init__
    self.t = Trade()
  File "I:\pythonWorkSpace\ctpServer\ai\iknow\ouyang\ctp_trade.py", line 79, in __init__
    self.h.RegisterUserSystemInfo.argtypes = [c_void_p, c_void_p]
  File "I:\tools\anaconda\envs\insight\lib\ctypes\__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "I:\tools\anaconda\envs\insight\lib\ctypes\__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'RegisterUserSystemInfo' not found

**Comment by ClTheDove** [comment]
请问解决了吗，我也遇到了这个问题
```
Traceback (most recent call last):
  File "G:\QH-hfpy\haifengat-atpy-master\atpy\main.py", line 11, in <module>
    atp = ATP()
  File "G:\QH-hfpy\haifengat-atpy-master\atpy\hfpy\atp.py", line 64, in __init__
    self.t = CtpTrade()
  File "G:\Program Files\Python3.7.4\lib\site-packages\py_ctp\trade.py", line 50, in __init__
    self.t = Trade()
  File "G:\Program Files\Python3.7.4\lib\site-packages\py_ctp\ctp_trade.py", line 79, in __init__
    self.h.RegisterUserSystemInfo.argtypes = [c_void_p, c_void_p]
  File "G:\Program Files\Python3.7.4\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "G:\Program Files\Python3.7.4\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'RegisterUserSystemInfo' not found
```

**Comment by kennyoysj** [comment]
没有啊

**Comment by kennyoysj** [comment]
> 请问解决了吗，我也遇到了这个问题
> 
> ```
> Traceback (most recent call last):
>   File "G:\QH-hfpy\haifengat-atpy-master\atpy\main.py", line 11, in <module>
>     atp = ATP()
>   File "G:\QH-hfpy\haifengat-atpy-master\atpy\hfpy\atp.py", line 64, in __init__
>     self.t = CtpTrade()
>   File "G:\Program Files\Python3.7.4\lib\site-packages\py_ctp\trade.py", line 50, in __init__
>     self.t = Trade()
>   File "G:\Program Files\Python3.7.4\lib\site-packages\py_ctp\ctp_trade.py", line 79, in __init__
>     self.h.RegisterUserSystemInfo.argtypes = [c_void_p, c_void_p]
>   File "G:\Program Files\Python3.7.4\lib\ctypes\__init__.py", line 377, in __getattr__
>     func = self.__getitem__(name)
>   File "G:\Program Files\Python3.7.4\lib\ctypes\__init__.py", line 382, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: function 'RegisterUserSystemInfo' not found
> ```

我直接下载了他的py_ctp的源码，然后把报错的代码注销了，目前可以连上
