### ISSUE TITLE
运行 test_api.py 后出现 AttributeError: function 'ReqLockInsert' not found

### ISSUE THREAD

**Issue by williamyizhu** [haifengat/hf_ctp_py_proxy#3]
Traceback (most recent call last):
  File ".\test_api.py", line 243, in <module>
    p = Test()
  File ".\test_api.py", line 42, in __init__
    self.t = Trade()
  File "\\vmware-host\Shared Folders\Downloads\hf_ctp_py_proxy-master\py_ctp\..\py_ctp\trade.py", line 108, in __init__
    self.h.ReqLockInsert.argtypes = [c_void_p, c_void_p, c_int32]
  File "C:\Users\William Yizhu\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\William Yizhu\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ReqLockInsert' not found

**Comment by haifengat** [comment]
已修复
